### ISSUE TITLE
About the runtime library

### ISSUE THREAD

**Issue by Ewardnewget** [lzto/bogo#1]
I am trying to use this project, however I got the following message when I compile the instrumented file: 
this is the command: g++ combine_out.o.s -o combine
/tmp/ccAXx2kF.o: In function `main':
combine_out.o:(.text+0x2ff): undefined reference to `__mpx_wrapper_malloc'
/tmp/ccAXx2kF.o: In function `llmpx_ctor':
combine_out.o:(.text+0x4ea2): undefined reference to `llmpx_rt_dummy_for_bring_in_ctor_dependency'
collect2: error: ld returned 1 exit status
I have put the .so and .o files to /usr/lib, What else should I do to make this work?
Thanks for your help!

**Comment by lzto** [comment]
it seems that the linking arguments are missing
try appending xxxxx.so at the end of your g++ command to see if it works

**Comment by lzto** [comment]
close due to inactivity, please reopen if needed.
-- Tong
